### PR TITLE
Draft: Display all Items and Slot Filtering

### PR DESCRIPTION
**Pull request by ech3lon42**
My attempt of Slot filtering and displaying all items, beware my experience with C++ is very limited.

- ~~by default all items are displayed instead of the current armor (this is mostly because I was too lazy to figure out how to add a <ALL> item at the top of the list). This could definitely be improved.~~ 
Fixed in [e28b122ef549c4](https://github.com/Xinaths/QuickArmorRebalance/pull/2/commits/e28b122ef549c4c2597a139a99d47f0b28653f78)
- Filter Items by Slot section added with checkboxes for all known slots.
- Items can be filtered to match the Slotmask in the following ways
  - item matches *at least* one of the masks of one or more selected slots (this is the default)
  - **Exact**: item matches the mask of one or more selected slots exactly
Use Case: Display Items that occupy exactly one specific slot 
  - **Reverse**: item does not match the mask of one or more selected slots
Use Case: For example one might select Slot 32 to show all body pieces and then activate Reverse to show anything but the Slot 32 body pieces.
  - **Bitwise**: Selected item slots in the GUI are combined before the matching proceeds.
Use Case: Exclude/Include Items matching multiple slots

**Performance** - I can definitely feel a performance drop, but even with thousands of armor mods it still seems to perform pretty well. I have a pretty powerful machine though and don't know how it would perform on a less capable system.

In my opinion this Plugin is more powerful than some equipment managers and much more powerful and easy to use than mods such as AddItemMenu.

I do understand that this type of usage was not intended and it would be perhaps better to provide that in a different mod altogether.

Feel free to use or refactor any parts of the code as needed. I can also do it if you point me into the right direction.

ImageGlass_2024-09-06_19-21-22

### CODE REVIEW

**Comment by ech3lon42** [comment]
I'm updating this to be better aligned with the latest version.

**Comment by ech3lon42** [comment]
Updated to new version and cleaned up some things in the UI.

- restore all of the existing functionality
- slot filtering works in all configurations now (all armors / all weapons / mod specific selections / currently worn armor)
- when slot filtering is not in use then corresponding UI elements are disabled

ImageGlass_2024-09-06_19-21-22

**Comment by Xinaths** [comment]
Sorry I wasn't keeping an eye on github, never expected someone to already be trying to make additions!

While I really appreciate the attempt at contributing, I want to use a different approach so will not be using these changes.

First, keeping the UI compact is extremely important to me, and adding a giant table is not going to work. The same functionality is being added, but its going to look more like this (still work in progress):
image

Second, the use of one variable per slot instead of arrays or bitmasks makes the code harder to maintain. I'm also planning to move the slot names away from being hard coded in the future so making sure to code in a way that's flexible for that.

The hotkey stuff might be fine but a bit hard to disentangle since its based off you're other changes. Also all this stuff is pretty quick to write once I sit down to do it so don't worry its not much of a time commitment =) More likely to spend an hour trying to get some ui element aligned right then writing the actual functionality.

I hope to push a new version with most, if not all, this functionality sometime tomorrow.

**Comment by ech3lon42** [comment]
Hey, I highly appreciate that you are willing to add some / perhaps most of the features.

I wasn't really expecting that you would merge this pull request because, as you noted, there are several issues with the maintainability of the code. If it serves as an idea / inspiration for the features that I was hoping for then that is great.

Also I will use your next commits as a learning opportunity to improve my C++ a little bit.

I don't know if you have time to look at it - but most of my ideas come from a [side project](https://github.com/ech3lon42/ECLoot/blob/main/) that I started some time ago. It is basically an equipment manager written in papyrus. The goal was to make browsing through the thousands of armor pieces the community has created easier and enable the creation of portable outfits for NPCs and player character. In my opinion it works very well but it's not exactly very user friendly at the moment.

When I saw your plugin all the building blocks were there to expand on that idea and basically make it the best equipment and portable armor/outfit/set manager available... by far. I was thinking of something like shown in the image below:

QAR-EQ

The rebalance tab would be the QAR as we know it now. The Equipment Manager tab would open the new interface. The functions are similar to what my side project is doing currently. But it would be much easier to use from this UI.

**Pull request closed without merging**
